### ISSUE TITLE
Maison Ikkoku

### ISSUE THREAD

**Issue by Pyfiend** [thegreatestminer/acp#18]
Hello,

I would like to request Maison Ikkoku please.  Thank you very much!

a fan

**Comment by thatanimeguy** [comment]
Well since this was requested... to complete Rumico Collection grab these @thegreatestminer:
https://bakabt.me/torrent/183423/maison-ikkoku-bd-1080p-kagura
https://bakabt.me/torrent/183622/maison-ikkoku-bangaihen-ikkokujima-nanpa-shimatsuki-maison-ikkoku-deserted-island-bd-bbt-rmx
https://bakabt.me/torrent/183623/maison-ikkoku-shiki-utsuriyuku-kisetsu-no-naka-de-maison-ikkoku-through-the-passing-of-the-seasons-bd-bbt-rmx
https://bakabt.me/torrent/183624/maison-ikkoku-kanketsu-hen-maison-ikkoku-final-chapter-bd-bbt-rmx


Other Rumico animes:
https://weeb.ztgasdf.workers.dev/Urusei%20Yatsura/
https://weeb.ztgasdf.workers.dev/Ranma%201-2/
https://weeb.ztgasdf.workers.dev/Inuyasha/

PS. Urusei Yatsura is the best out of them, currently watching Inuyasha. Another masterpiece. And least favourite is Maison Ikkoku.

**Comment by seedtheworld** [comment]
Well since this was requested... to complete Rumico Collection grab these @thegreatestminer:

https://bakabt.me/torrent/183423/maison-ikkoku-bd-1080p-kagura
https://bakabt.me/torrent/183622/maison-ikkoku-bangaihen-ikkokujima-nanpa-shimatsuki-maison-ikkoku-deserted-island-bd-bbt-rmx
https://bakabt.me/torrent/183623/maison-ikkoku-shiki-utsuriyuku-kisetsu-no-naka-de-maison-ikkoku-through-the-passing-of-the-seasons-bd-bbt-rmx
https://bakabt.me/torrent/183624/maison-ikkoku-kanketsu-hen-maison-ikkoku-final-chapter-bd-bbt-rmx

Other Rumico animes:
https://weeb.ztgasdf.workers.dev/Urusei%20Yatsura/
https://weeb.ztgasdf.workers.dev/Ranma%201-2/
https://weeb.ztgasdf.workers.dev/Inuyasha/

PS. Urusei Yatsura is the best out of them, currently watching Inuyasha. Another masterpiece. And least favourite is Maison Ikkoku.

**Comment by thegreatestminer** [comment]
@seedtheworld I'm not too keen on getting Kagura's release, as commenters have mentions various problems with subtitles and timing. I can get sxales's release instead, and I can get the other three torrents.

Workin' on it!

**Comment by thegreatestminer** [comment]
Actually, just for archive purposes, I'll get Kagura's release as well.

**Comment by thegreatestminer** [comment]
These files won't be available due to my ratio being shit in BakaBT. No one is downloading from my seeded torrents ;w;

```
[BBT-RMX][QTS] Maison Ikkoku - Gekijou Yokoku Hen 1 (BD H264 1662x900 AAC) [1543C84D].mkv
[BBT-RMX][QTS] Maison Ikkoku - Gekijou Yokoku Hen 2 (BD H264 1662x900 AAC) [FC7B807E].mkv
```

The actual file, `[BBT-RMX][QTS] Maison Ikkoku - Kanketsu Hen (BD H264 1662x900 AAC 1.0+2.0) [5184F007].mkv` will be available because AnimeKaizoku has a mirror of that file.

**Comment by seedtheworld** [comment]
Don't sweat it. I never really cared for it. I offered those just for archive purposes. Plus Kagura's just raws, you can grab better subs literally anywhere.

**Comment by thegreatestminer** [comment]
Yeah, that's the glory of softsubs.

I'm getting sxales's releases, and boy are most of them slow.
![image](https://user-images.githubusercontent.com/19188146/85301324-af184c80-b475-11ea-8abe-98b30e510b2d.png)

**Comment by seedtheworld** [comment]
Hang in there mate😅

**Comment by seedtheworld** [comment]
Why not cancel sxales release and just add these subs to Kagura's 
https://animetosho.org/storage/torattachpk/289015/%5BRPG-sama%5D%20Maison%20Ikkoku%20%28BDRip%20Dual%20960x720%20x264%20AAC%29_attachments.7z

**Comment by thegreatestminer** [comment]
I mean, sure, why not. Takes less time for me XD

**Comment by thegreatestminer** [comment]
Alright, I got most of it. I want to get sxales's releases as well, but everything else has finished.

http://weeb.ztgasdf.workers.dev/Maison%20Ikkoku/

---

On a side note, I added the entirety of the Ghost in the Shell series!

https://weeb.ztgasdf.workers.dev/Ghost%20in%20the%20Shell/

**Comment by seedtheworld** [comment]
@thegreatestminer I always wanted to watch Ghost in the Shell. So how do I go on about it. Where to start?

**Comment by Pyfiend** [comment]
![viewing order](https://user-images.githubusercontent.com/67236709/85484877-8b8bf980-b57c-11ea-953d-40b208e66274.jpg)
Try this

**Comment by Pyfiend** [comment]
p.s.  Thank you all VERY MUCH for fulfilling my request for Maison Ikkoku. ^__^
