### ISSUE TITLE
subtitles in a non-English language

### ISSUE THREAD

**Issue by Pyfiend** [thegreatestminer/acp#22]
Hello again:  In the file path (directory "Dungeon ni Deai o Motomeru no wa Machigatte Iru Darouka" --> sub-dir "[VCB-Studio] DanMachi" -->sub-sub-dir "[DHR&MakariHoshiyume&VCB-Studio] DanMachi II [Ma10p_1080p]"), all of the subtitle files that accompany these 2nd season episodes are in Chinese, not English.  Would you happen to have the English ones?  Thank you again.

**Comment by thegreatestminer** [comment]
This release only has external Chinese subtitles, and is intentional. You can use https://weeb.ztgasdf.workers.dev/Dungeon%20ni%20Deai%20o%20Motomeru%20no%20wa%20Machigatte%20Iru%20Darouka/[Aeenald]%20DanMachi%20S2%20+%20OVA%20_%20Dungeon%20ni%20Deai%20o%20Motomeru%20no%20wa%20Machigatteiru%20Darouka%20Familia%20Myth%20II%20+%20OVA%20_%20Is%20It%20Wrong%20to%20Try%20to%20Pick%20Up%20Girls%20in%20a%20Dungeon%20Season%202%20+%20OVA%20[BDrip%201080p%20HEVC%20X265%2010-bit]%20[AAC%202.0]_at.7z for English subtitles.

**Comment by Pyfiend** [comment]
Those sub files work great.  Thanks again!!!
